--  LAB 5 MULTIPLE TABLES
--  Put your answers on the lines after each letter. E.g. your query for question 1A should go on line 5; your query for question 1B should go on line 7...
--  1 
-- A 
SELECT * from sales where item="1014";
-- B 
SELECT sales.date,stock_items.item FROM stock_items INNER JOIN sales ON stock_items.id=sales.item WHERE sales.item="1014"; 

--  2
-- A 
SELECT * FROM sales WHERE employee="111";

-- B
SELECT sales.date,employees.first_name, employees.last_name,sales.item FROM sales INNER JOIN employees ON employees.id=sales.employee WHERE sales.employee="111";

--  3
SELECT sales.date, sales.item, employees.first_name FROM sales  JOIN employees  ON sales.employee = employees.id WHERE sales.date BETWEEN '2024-09-12' AND '2024-09-18';
-- B
SELECT employees.first_name, employees.last_name, COUNT(sales.id) AS sales_count FROM sales  JOIN employees  ON sales.employee = employees.id GROUP BY employees.first_name, employees.last_name ORDER BY sales_count DESC;

--  4
-- A   
  SELECT sal.date, sto.item, sto.price, sto.category, emp.first_name FROM sales sal JOIN stock_items sto ON sal.item = sto.id JOIN employees emp ON sal.employee = emp.id WHERE sal.employee = (SELECT emp.id FROM sales sal JOIN employees emp ON sal.employee = emp.id GROUP BY emp.id ORDER BY COUNT(sal.id) DESC LIMIT 1);
-- B
SELECT sto.id, sto.item, sto.price, sto.category, COUNT(sal.id) AS times_sold FROM stock_items sto LEFT JOIN sales sal ON sto.id = sal.item GROUP BY sto.id ORDER BY sto.id;

--  5
-- A  A What is the total revenue generated by each employee from items they sold, grouped by employee and ordered by the highest revenue?
-- B
SELECT e.first_name, e.last_name, SUM(si.price) AS total_revenue FROM sales s JOIN employees e ON s.employee = e.id JOIN stock_items si ON s.item = si.id GROUP BY e.first_name, e.last_name ORDER BY total_revenue DESC;